# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    always_declare_return_types: true
    avoid_unnecessary_containers: true
    prefer_final_locals: true